version: '3.8'

services:
  keycloak:
    # docs:
    # https://blog.codecentric.de/en/2021/12/keycloak-keycloak-x/
    # https://www.keycloak.org/2020/12/first-keycloak-x-release.adoc
    # https://keycloak.discourse.group/t/differences-between-keycloak-and-keycloak-x-docker-images/9459/4
    # https://github.com/keycloak/keycloak-containers/blob/16.1.1/server/README.md
    # https://github.com/keycloak/keycloak-community/blob/main/design/keycloak.x/configuration.md#databaseq
    #
    # Usage from app: https://quarkus.io/guides/security-keycloak-authorization
    container_name: starter-keycloak
    image: quay.io/keycloak/keycloak-x
    # https://github.com/keycloak/keycloak-community/blob/main/design/keycloak.x/configuration.md
    command: start-dev --http-port=8180 --db=postgres --db-url=jdbc:postgresql://localhost:5432/starter-dev-keycloak --db-username=starter-dev-keycloak --db-password=starter-dev-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    network_mode: host

#  dynamo:
#    container_name: abp-sam-nestjs-dynamodb
#    image: amazon/dynamodb-local
#    networks:
#      - backend
#    ports:
#      - '8000:8000'
#    volumes:
#      - dynamodata:/home/dynamodblocal
#    working_dir: /home/dynamodblocal
#    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath .'
#
#networks:
#  backend:
#    name: abp-sam-backend
#
#volumes:
#  dynamodata: {}
