version: '3.8'

services:
  keycloak:
    container_name: starter-keycloak
    image: quay.io/keycloak/keycloak-x
    # https://github.com/keycloak/keycloak-community/blob/main/design/keycloak.x/configuration.md
    command: start-dev --http-port=8180 --db=postgres --db-url=jdbc:postgresql://localhost:5432/starter-dev-keycloak --db-username=starter-dev-keycloak --db-password=starter-dev-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    network_mode: host